services:
  db:
    image: postgres:15
    container_name: leads-postgres
    restart: always
    environment:
      POSTGRES_DB: leads_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./php-backend/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  php:
    build: ./php-backend
    container_name: php-backend
    restart: always
    depends_on:
      - db
    volumes:
      - ./php-backend:/var/www
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: leads_db
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: super_long_secure_jwt_secret_here

  nginx:
    image: nginx:alpine
    container_name: php-nginx
    restart: always
    depends_on:
      - php
    ports:
      - "8081:80"
    volumes:
      - ./php-backend:/var/www
      - ./php-backend/docker/nginx.conf:/etc/nginx/conf.d/default.conf

  frontend:
    build: ./frontend
    container_name: vue-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - nginx